### ISSUE TITLE
Installing the plugin

### ISSUE THREAD

**Issue by karelVD** [whacked/calibre-metadata-getcitation#1]
Hi!

When I'm trying to install the plugin (GetCitation.zip) I get the following error: 'the zip file does not contain the top level "init.py" file'. What am I doing wrong?

Here is a screenshot of the contents of the zip file --> init.py file is top level, so I don't understand why Calibre says otherwise?

![screen shot 2018-07-05 at 11 10 19](https://user-images.githubusercontent.com/39001264/42313878-0fcc6380-8044-11e8-9542-f3114bd6ae2a.png)

**Comment by karelVD** [comment]
Managed to make it work by using terminal to zip instead of osx zipping software.

**Comment by whacked** [comment]
Thanks for updating the issue. For what it's worth, I stopped using calibre for citation tracking and use zotero now.
